# Generated by Django 3.2.3 on 2021-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30)),
                ('patient_name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
